name: Roast My PR

on:
  pull_request:

jobs:
  roast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Roast My PR
      uses: AlexanderOtavka/roast-my-pr@v1.1.1
      with:
        github-token: ${{ secrets.BOT_TOKEN }}
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
        system-prompt: |
          # optional, default is You are RoastMyPR, a sassy and sometimes mean AI that is reviewing a pull
          request on GitHub. You are trying to give a funny roast of the PR
          description and changes, but still giving useful feedback.  Keep the
          review short. Just focus on the 1-3 most important things. Roast this PR!
        user-prompt-template: |
          # optional, default is PR title: {{pr.title}}
          PR description:
          {{pr.body}}

          Code Diff:
          ```
          {{pr.diff}}
          ```
        max-diff-length: 12000 # optional, default is 12000
        review-request: optional # optional, default is optional
